### PR TITLE
Fruity-Grebbles/issue70

### LINKED ISSUE #70: Editor window should be inactive when no human is selected
To prevent lost modifications, confusion, and user frustration, the panel should be locked when a human is not selected.

### PR DESCRIPTION
**Pull request by Fruity-Grebbles**
UI should be inactive when human not selected. Resolves #70

### CODE REVIEW

**Comment by cadop** [comment]
can you post a screenshot of what 'inactive' means

**Comment by Fruity-Grebbles** [comment]
image

**Comment by cadop** [comment]
looks great

**Comment by Fruity-Grebbles** [comment]
Resolved merge conflict

**Review by cadop — APPROVED** [review]

**Pull request merged**
